src/config/routes.rb
Rails.application.routes.draw do
  resources :warehouses
  post 'warehouses/:id/increase', to: 'warehouses#inc'
  post 'warehouses/:id/decrease', to: 'warehouses#dec'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/warehouse.rb
class Warehouse < ApplicationRecord
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

src/app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: %i[ inc dec update destroy ]

  # GET /warehouses or /warehouses.json
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # POST /warehouses/1/inc
  def inc
    @warehouse.count += 1
    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to warehouses_url, notice: "Warehouse was successfully created." }
        format.json { render :index, status: :created, location: @warehouse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /warehouses/1/dec
  def dec
    @warehouse.count -= 1
    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to warehouses_url, notice: "Warehouse was successfully created." }
        format.json { render :index, status: :created, location: @warehouse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /warehouses or /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to warehouses_url, notice: "Warehouse was successfully created." }
        format.json { render :index, status: :created, location: @warehouse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1 or /warehouses/1.json
  def destroy
    @warehouse.destroy
    respond_to do |format|
      format.html { redirect_to warehouses_url, notice: "Warehouse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warehouse_params
      params.require(:warehouse).permit(:name, :count, :category)
    end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/warehouses_helper.rb
module WarehousesHelper
end

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Src</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

src/app/views/warehouses/_form.html.erb
<%= form_with(model: warehouse) do |form| %>
  <% if warehouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
        <% warehouse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/warehouses/edit.html.erb
<h1>Editing Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Show', @warehouse %> |
<%= link_to 'Back', warehouses_path %>

src/app/views/warehouses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Warehouses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @warehouses.each do |warehouse| %>
      <tr>
        <td><%= warehouse.name %></td>
        <td><%= warehouse.count %></td>
        <td><%= warehouse.category %></td>
        <td><%= link_to 'Increase', "/warehouses/#{warehouse[:id]}/increase", method: :post %></td>
        <td><%= link_to 'Decrease', "/warehouses/#{warehouse[:id]}/decrease", method: :post %></td>
        <td><%= link_to 'Destroy', warehouse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Warehouse', new_warehouse_path %>

src/app/views/warehouses/new.html.erb
<h1>New Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Back', warehouses_path %>

src/app/views/warehouses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @warehouse.name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @warehouse.count %>
</p>

<p>
  <strong>Category:</strong>
  <%= @warehouse.category %>
</p>

<%= link_to 'Edit', edit_warehouse_path(@warehouse) %> |
<%= link_to 'Back', warehouses_path %>